# Trainer config (PyTorch Lightning, stub).
accelerator: gpu
devices: 1
precision: 16-mixed
batch_size: 128
lr: 0.001
dropout: 0.4
max_grad_norm: 1.0
early_stopping_patience: 10
max_iters: 100
repeats: 10
ensemble: true
